language: python
python:
  - 2.7
# services:
#   - mongodb
before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo apt-get install -y mongodb-org=2.6.7
  - sudo apt-get install libgeos-dev gdal-bin libgdal1h libgdal-dev
  - sudo /usr/share/elasticsearch/bin/plugin -install elasticsearch/elasticsearch-analysis-icu/2.4.0
  - sudo service elasticsearch start
  - mongo --version
install:
  - pip install -r requirements/travis.pip
  - pip install --no-deps -e .
script:
  - nosetests --with-coverage udata
after_success:
  - coveralls --rcfile=coverage.rc
